"use client";

// Component for displaying expense forecast generated by AI
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  CardFooter,
} from "@/components/ui/card";
import { PrevisaoGastos } from "@/types";
import { formatarMoeda } from "@/utils/formatadores";
import { Button } from "@/components/ui/button";
import {
  Calendar,
  TrendingUp,
  CircleDollarSign,
  ArrowRight,
} from "lucide-react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useState } from "react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
  Cell,
} from "recharts";
import { CORES_GRAFICOS } from "@/constants/format";

interface ExpenseForecastProps {
  forecast: PrevisaoGastos;
  onViewDetailedReport?: () => void;
}

export function ExpenseForecast({
  forecast,
  onViewDetailedReport,
}: ExpenseForecastProps) {
  const [selectedMonth, setSelectedMonth] = useState<string>(
    forecast.previsao.length > 0 ? forecast.previsao[0].mes : ""
  );

  // Find the selected month data
  const selectedMonthData = forecast.previsao.find(
    (m) => m.mes === selectedMonth
  );

  // Prepare data for the bar chart
  const prepareChartData = () => {
    if (!selectedMonthData) return [];

    // Get top 5 categories by value
    const categories = Object.entries(selectedMonthData.categorias)
      .map(([name, value]) => ({ name, value }))
      .sort((a, b) => b.value - a.value)
      .slice(0, 5);

    return categories;
  };

  const chartData = prepareChartData();

  // Generate a fixed color palette for categories
  const categoryColors = [
    CORES_GRAFICOS.PALETA[0],
    CORES_GRAFICOS.PALETA[1],
    CORES_GRAFICOS.PALETA[2],
    CORES_GRAFICOS.PALETA[3],
    CORES_GRAFICOS.PALETA[4],
  ];

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <TrendingUp className="w-5 h-5 text-blue-600" />
          Previsão de Gastos
        </CardTitle>
        <CardDescription>
          Projeção de gastos futuros baseada no seu histórico
        </CardDescription>
      </CardHeader>

      <CardContent className="space-y-5">
        {/* Month selector */}
        <div className="flex items-center gap-3">
          <Calendar className="w-4 h-4 text-muted-foreground" />
          <Select value={selectedMonth} onValueChange={setSelectedMonth}>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Selecione o mês" />
            </SelectTrigger>
            <SelectContent>
              {forecast.previsao.map((item) => (
                <SelectItem key={item.mes} value={item.mes}>
                  {item.mes}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Total projected expenses */}
        {selectedMonthData && (
          <div className="flex items-center gap-3 p-3 bg-blue-50 rounded-lg border border-blue-100">
            <CircleDollarSign className="w-10 h-10 text-blue-600" />
            <div>
              <p className="text-sm text-blue-700">
                Total previsto para {selectedMonth}
              </p>
              <p className="text-2xl font-bold text-blue-900">
                {formatarMoeda(selectedMonthData.total)}
              </p>
            </div>
          </div>
        )}

        {/* Bar chart with top 5 categories */}
        {chartData.length > 0 && (
          <div className="pt-2">
            <h4 className="text-sm font-medium mb-3">
              Principais categorias previstas:
            </h4>
            <div className="h-60">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart
                  layout="vertical"
                  width={500}
                  height={300}
                  data={chartData}
                  margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
                >
                  <CartesianGrid strokeDasharray="3 3" horizontal={false} />
                  <XAxis
                    type="number"
                    tickFormatter={(value) =>
                      formatarMoeda(value).replace("R$", "")
                    }
                  />
                  <YAxis
                    dataKey="name"
                    type="category"
                    width={100}
                    tickFormatter={(value) =>
                      value.length > 14 ? `${value.substring(0, 13)}...` : value
                    }
                  />
                  <Tooltip
                    formatter={(value) => formatarMoeda(value as number)}
                  />
                  <Bar dataKey="value" fill="#8884d8">
                    {chartData.map((entry, index) => (
                      <Cell
                        key={`cell-${index}`}
                        fill={categoryColors[index % categoryColors.length]}
                      />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        )}

        {/* AI explanation */}
        <div className="pt-2 border-t text-sm text-muted-foreground">
          <p>{forecast.explicacao}</p>
        </div>
      </CardContent>

      {onViewDetailedReport && (
        <CardFooter>
          <Button
            variant="outline"
            onClick={onViewDetailedReport}
            className="w-full"
          >
            Ver relatório detalhado
            <ArrowRight className="w-4 h-4 ml-2" />
          </Button>
        </CardFooter>
      )}
    </Card>
  );
}
